# Generated by Django 3.2.8 on 2021-10-26 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Air',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('temperature', models.FloatField()),
                ('humidity', models.FloatField()),
                ('conzentration', models.FloatField()),
                ('pm25', models.FloatField()),
                ('mp100', models.FloatField()),
            ],
        ),
    ]
