# Generated by Django 3.2.8 on 2021-10-30 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='air',
            name='conzentration',
        ),
    ]
