# Generated by Django 3.2.8 on 2021-11-10 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0002_remove_air_conzentration'),
    ]

    operations = [
        migrations.CreateModel(
            name='fAir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('temperature', models.FloatField()),
                ('humidity', models.FloatField()),
                ('pm25', models.FloatField()),
                ('mp100', models.FloatField()),
            ],
        ),
        migrations.RenameModel(
            old_name='Air',
            new_name='uAir',
        ),
    ]
